import { jsPDF } from "jspdf";

/**
 * intake  = { name, email, date }
 * assessment = { symptoms:[], summary:"", riskScore: number(0-100), recommendations:"" }
 */
export function generatePDF(intake = {}, assessment = {}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 40;
  let y = 50;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("SereneMind — Health Summary", 297.5, y, { align: "center" });
  y += 24;

  doc.setDrawColor(130, 150, 255);
  doc.setLineWidth(1);
  doc.line(marginX, y, 555, y);
  y += 16;

  // Intake
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Full Name: ${intake.name || ""}`, marginX, y); y += 18;
  doc.text(`Email: ${intake.email || ""}`, marginX, y); y += 18;
  doc.text(`Date: ${intake.date || ""}`, marginX, y); y += 26;

  // Summary
  doc.setFont("helvetica", "bold");
  doc.text("Summary", marginX, y); y += 14;
  doc.setFont("helvetica", "normal");
  y = writeWrapped(doc, assessment.summary || "—", marginX, y, 515);

  // Symptoms
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Symptoms Reported", marginX, y); y += 14;
  doc.setFont("helvetica", "normal");
  const list = assessment.symptoms && assessment.symptoms.length ? assessment.symptoms : ["—"];
  list.forEach((s) => { y = addLine(doc, `• ${s}`, marginX, y); });

  // Risk
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Risk Score", marginX, y); y += 14;
  doc.setFont("helvetica", "normal");
  y = addLine(doc, `${assessment.riskScore ?? "—"} / 100`, marginX, y);

  // Recommendations
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Recommendations", marginX, y); y += 14;
  doc.setFont("helvetica", "normal");
  y = writeWrapped(doc, assessment.recommendations || "—", marginX, y, 515);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by SereneMind (confidential)", marginX, 810);

  const filename = `SereneMind_Report_${(intake.name || "user").replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}

/* helpers */
function writeWrapped(doc, text, x, y, maxWidth) {
  const lines = doc.splitTextToSize(text, maxWidth);
  lines.forEach((line) => { y = addLine(doc, line, x, y); });
  return y;
}
function addLine(doc, line, x, y) {
  if (y > 760) { doc.addPage(); y = 50; }
  doc.text(line, x, y);
  return y + 16;
}