// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlhtfdbpljtvlbmewym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bGh0ZmRicGxqdHZsYm1ld3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTA0NDAsImV4cCI6MjA3MjEyNjQ0MH0.ZNTNgyGsDKqplPnehBXcwWProu9zo7NoYLy1AS9yLUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});